export const banksList = [
  { label: "Banco do Brasil", value: "Banco do Brasil", codigo: "001" },
  { label: "Bradesco", value: "Bradesco", codigo: "237" },
  {
    label: "Caixa Econômica Federal",
    value: "Caixa Econômica Federal",
    codigo: "104",
  },
  { label: "Itaú", value: "Itaú", codigo: "341" },
  { label: "Nubank", value: "Nubank", codigo: "260" },
  { label: "Santander", value: "Santander", codigo: "033" },
  { label: "Inter", value: "Inter", codigo: "077" },
  { label: "Original", value: "Original", codigo: "212" },
  { label: "Safra", value: "Safra", codigo: "422" },
  { label: "Stone", value: "Stone" },
  { label: "Pan", value: "Pan", codigo: "623" },
  { label: "PicPay", value: "PicPay" },
  { label: "B3", value: "B3" },
  { label: "Neon", value: "Neon", codigo: "735" },
  { label: "AgiBank", value: "AgiBank", codigo: "121" },
  { label: "BTG Pactual", value: "BTG Pactual", codigo: "208" },
  { label: "BMG", value: "BMG", codigo: "318" },
  { label: "C6", value: "C6", codigo: "336" },
  { label: "Digio", value: "Digio" },
  { label: "BS2", value: "BS2", codigo: "218" },
  { label: "Modal", value: "Modal", codigo: "746" },
  { label: "Banco do Nordeste", value: "Banco do Nordeste", codigo: "004" },
  { label: "Banrisul", value: "Banrisul", codigo: "041" },
  { label: "Sicredi", value: "Sicredi", codigo: "748" },
  { label: "Sicoob", value: "Sicoob", codigo: "756" },
  { label: "Mercantil do Brasil", value: "Mercantil do Brasil", codigo: "389" },
  { label: "Citibank", value: "Citibank", codigo: "745" },
  { label: "HSBC Brasil", value: "HSBC Brasil", codigo: "738" },
  { label: "JP Morgan", value: "JP Morgan", codigo: "376" },
  { label: "Banco Votorantim", value: "Banco Votorantim", codigo: "655" },
  { label: "Banco ABC Brasil", value: "Banco ABC Brasil", codigo: "246" },
  { label: "Banco Fibra", value: "Banco Fibra", codigo: "224" },
  { label: "Banco da Amazônia", value: "Banco da Amazônia", codigo: "003" },
  {
    label: "Banco do Estado de Sergipe",
    value: "Banco do Estado de Sergipe",
    codigo: "047",
  },
  { label: "Banco Pine", value: "Banco Pine", codigo: "643" },
  { label: "Banco ModalMais", value: "Banco ModalMais", codigo: "746" },
  { label: "Banco Topázio", value: "Banco Topázio", codigo: "082" },
  { label: "Cora", value: "Cora", codigo: "403" },
  { label: "PagSeguro", value: "PagSeguro", codigo: "290" },
  { label: "Banco Renner", value: "Banco Renner", codigo: "654" },
  { label: "Banco Sofisa", value: "Banco Sofisa", codigo: "637" },
  { label: "Banco Daycoval", value: "Banco Daycoval", codigo: "707" },
  { label: "Banco XP", value: "Banco XP", codigo: "102" },
];
